USE RETAIL;

SELECT * FROM CUSTOMER;
SELECT PRODNAME, PRICE FROM PRODUCT;
SELECT * FROM ORDERS WHERE QTY > 2;
SELECT * FROM PRODUCT WHERE PRICE BETWEEN 200 AND 1000;
SELECT * FROM CUSTOMER WHERE ADDRESS LIKE '%Street%';
SELECT * FROM PRODUCT WHERE CATID = 1 OR CATID = 2;
SELECT * FROM ORDERS WHERE CUSTID = 1 AND PRODID = 1;
SELECT * FROM SUPPLIER WHERE SUPNAME LIKE 'P%';
SELECT * FROM CUSTOMER ORDER BY FULLNAME ASC;
SELECT * FROM PRODUCT ORDER BY PRICE DESC LIMIT 3;
SELECT * FROM ORDERS ORDER BY ORDERDATE DESC LIMIT 5;
